version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  producer:
    build: ./producer-svc
    ports:
      - "3000:3000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq

  consumer:
    build: ./consumer-svc
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq

networks:
  rabbitmq:
    driver: bridge